language: node_js
node_js:
 - "node"

cache: npm

script: npm run build

deploy:
 provider: pages
 skip_cleanup: true
 github_token: db0fdd76a8a191fb7b05000dcca666cc949b3732
 local_dir: dist
 on:
   branch: master
